---
train:
  params:
    batch_size: 256
    epoch: 20
    lr: 0.001
    decay: 0.1
    decay_step: 75000
    loss: MSELoss
  save:
    save_path: "/home/zhuzi/code/GazeEstimation/baseline/2_itracker/2_iter-gc"
    model_name: Itracker
    step: 10
  data:
    image: "/data/4_gc/2_gcout/Image"
    label: "/data/4_gc/2_gcout/Label/train"
  pretrains: "None"
test:
   load:
      begin_step: 20
      end_step: 20
      steps: 10
      load_path: "/home/zhuzi/code/GazeEstimation/baseline/2_itracker/2_iter-gc"
      model_name: Itracker
   data:
      image: "/data/4_gc/2_gcout/Image"
      label: "/data/4_gc/2_gcout/Label/test"
reader: reader_gc
