---
train:
  params:
    batch_size: 256
    epoch: 20
    lr: 0.001
    decay: 0.1
    decay_step: 75000
    loss: MSELoss
  save:
    save_path: "."
    model_name: Itracker
    step: 5
  data:
    image: "/data/3_EyeDiapOutPut/Image"
    label: "/data/3_EyeDiapOutPut/Label"
  pretrains: "None"
test:
   load:
      begin_step: 5
      end_step: 20
      steps: 5
      load_path: "."
      model_name: Itracker
   data:
      image: "/data/3_EyeDiapOutPut/Image"
      label: "/data/3_EyeDiapOutPut/Label"
reader: eyediap
