---
train:
  params:
    batch_size: 512
    epoch: 20
    lr: 0.001
    decay: 0.5
    decay_step:
      - 1
  save:
    save_path: "."
    model_name: "diff-nn"
    step: 2
  data:
    path: "/data/4_gc/2_gcout/"
test:
   load:
      begin_step: 8
      end_step: 12
      steps: 1
      model_name: "diff-nn"
      load_path: "."
   data:
      path: "/data/4_gc/2_gcout"
