---
train:
  params:
    batch_size: 256
    epoch: 12
    lr: 0.001
    decay: 0.1
    decay_step:
      - 8
  save:
    save_path: "."
    model_name: "AFF-Net"
    step: 1
  data:
    path: "/data/4_gc/2_gcout/"
test:
   load:
      begin_step: 8
      end_step: 12
      steps: 1
      model_name: "AFF-Net"
      load_path: "."
   data:
      path: "/data/4_gc/2_gcout"
